#Statistics plots
#Loading data tables...
#het <- read.table("/Users/sanderwvanderlaan", header = T)
#ibd <- read.table("/Users/sanderwvanderlaan", header = T)


#Statistics plots after strict QC and LD-pruning
#Inbreeding coefficient
pdf(file="20101229aesnp5fwd_xatcgqcprunedbhm2het.FSTAT.pdf")
hist(het$F, breaks=100, main="Heterozygosity", xlab="Inbreeding coefficient (F-statistic)", ylab="# Samples", xlim=c(-0.13,0.13),  col="steelblue", cex.axis="0.8")
abline(v=mean(het$F), col="black")
abline(v=mean(het$F)-3*sd(het$F), lty=2, col="red")
abline(v=mean(het$F)+3*sd(het$F), lty=2, col="red")
dev.off()
postscript(file="20101229aesnp5fwd_xatcgqcprunedbhm2het.FSTAT.eps",width=10, height=10,paper="special",horizontal=FALSE)
hist(het$F, breaks=100, main="Heterozygosity", xlab="Inbreeding coefficient (F-statistic)", ylab="# Samples", xlim=c(-0.13,0.13),  col="steelblue", cex.axis="0.8")
abline(v=mean(het$F), col="black")
abline(v=mean(het$F)-3*sd(het$F), lty=2, col="red")
abline(v=mean(het$F)+3*sd(het$F), lty=2, col="red")
dev.off()

#Identity-by-descent
pdf(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBD.pdf")
hist(ibd$PI_HAT, breaks=100, main="Idenity-By-Descent (IBD)", xlab="Proportion IBD (pi-hat)", ylab="# Sample pairs", col="steelblue", cex.axis="0.8")
abline(v=0.2, lty=2, col="red")
dev.off()
postscript(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBD.eps",width=10, height=10,paper="special",horizontal=FALSE)
hist(ibd$PI_HAT, breaks=100, main="Idenity-By-Descent (IBD)", xlab="Proportion IBD (pi-hat)", ylab="# Sample pairs", col="steelblue", cex.axis="0.8")
abline(v=0.2, lty=2, col="red")
dev.off()
pdf(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBDlim.pdf")
hist(ibd$PI_HAT, breaks=100, main="Idenity-By-Descent (IBD)", xlab="Proportion IBD (pi-hat)", ylab="# Sample pairs", ylim=c(0,150), col="steelblue", cex.axis="0.8")
abline(v=0.2, lty=2, col="red")
dev.off()
postscript(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBDlim.eps",width=10, height=10,paper="special",horizontal=FALSE)
pdf(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBDlim.pdf")
hist(ibd$PI_HAT, breaks=100, main="Idenity-By-Descent (IBD)", xlab="Proportion IBD (pi-hat)", ylab="# Sample pairs", ylim=c(0,150), col="steelblue", cex.axis="0.8")
abline(v=0.2, lty=2, col="red")
dev.off()
pdf(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBDscatter.pdf")
library("geneplotter")
colors  <- densCols(ibd$Z0, ibd$Z1)
plot(ibd$Z0, ibd$Z1, main="Idenity-By-Descent (IBD) per sample-pair", col=colors, xlab="Proportion markers identical by descent (Z0)", ylab="Proportion markers identical by descent (Z1)", xlim=c(0,1), ylim=c(0,1), pch=20, cex.axis="0.8", axes=F)
axis(2,at=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0))
axis(1,at=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0))
abline(h=0.05,lty=2,col="red")
abline(v=0.95,lty=2,col="red")
dev.off()
postscript(file="20101229aesnp5fwd_xatcgqcprunedbhm2_genome.IBDscatter.eps", paper="special", width=10, height=10,horizontal=FALSE)
library("geneplotter")
colors  <- densCols(ibd$Z0, ibd$Z1)
plot(ibd$Z0, ibd$Z1, main="Idenity-By-Descent (IBD) per sample-pair", col=colors, xlab="Proportion markers identical by descent (Z0)", ylab="Proportion markers identical by descent (Z1)", xlim=c(0,1), ylim=c(0,1), pch=20, cex.axis="0.8", axes=F)
axis(2,at=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0))
axis(1,at=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0))
abline(h=0.05,lty=2,col="red")
abline(v=0.95,lty=2,col="red")
dev.off()

